config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root 'portal#index'

    resources :search, only: :index, as: :searches
    resources :services, only: :show

    resources :topics, only: :show, path: 'browse' do
      resources :topics, only: :show, as: :subtopic, path: ''
    end

    resource :status, only: [:show]

    namespace :support_interface, path: '/support' do
      root 'services#index'

      resources :topics, only: %i[index new create]
      resources :sessions, only: :new
      resources :services, only: %i[new create update edit]
    end
  end

  post '/auth/:provider/callback', to: 'support_interface/sessions#create'
  post '/auth/failure', to: 'support_interface/sessions#failure'
  get '/auth/failure', to: 'support_interface/sessions#failure'
  get '/logout', to: 'support_interface/sessions#destroy'
end

app/models/service.rb
class Service < ApplicationRecord
  has_one :service_topic
  has_one :topic, through: :service_topic
  has_many :service_requirements, dependent: :destroy

  validates :name, :website, :locale, presence: true

  scope :locale, ->(locale) { where(locale: locale) }
  scope :by_name, ->(term) { where('unaccent(name) ilike unaccent(?)', "%#{term}%") }
  scope :by_description, ->(term) { where('description ilike unaccent(?)', "%#{term}%") }
  scope :results, ->(term) { by_name(term).or(by_description(term)) }
  scope :localised_results, ->(term, locale) { Service.locale(locale).where(slug: results(term).pluck(:slug)) }

  enum locale: {
    en: 'English',
    el: 'Greek'
  }

  enum availability: {
    temporarily_unavailable: 0,
    not_found: 1,
    ok: 2
  }
  def to_param
    slug
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def show
    @service = Service.locale(I18n.locale).find_by(slug: service_id)

    respond_to do |format|
      format.html { redirect_to @service.website, allow_other_host: true unless show_information_page?(@service) }
      format.json { render json: @service }
    end
  end

  private

  def service_id
    params.permit(:id)[:id]
  end

  def show_information_page?(service)
    service.information.present? && redirect_param_set?
  end

  def redirect_param_set?
    !params['redirect'] || params['redirect'] != 'true'
  end
end

app/controllers/support_interface/application_controller.rb
module SupportInterface
  class ApplicationController < ActionController::Base
    include Localisation

    layout 'application_support'

    before_action :authenticate_user!

    helper_method :current_user

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
    end

    def authenticate_user!
      redirect_to new_support_interface_session_path if session[:user_id].nil?
    end
  end
end

app/controllers/support_interface/services_controller.rb
module SupportInterface
  class ServicesController < ApplicationController
    def index
      @services = Service.locale(I18n.locale)
    end

    def new
      @service_form = ServiceForm.new
    end

    def create
      @service_form = ServiceForm.new(new_service_form_params)

      if @service_form.valid?(:new)
        @service_form.save!
        redirect_to support_interface_root_path, notice: t('.success')
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      service_en = Service.locale('en').find_by(slug: service_slug)
      service_el = Service.locale('el').find_by(slug: service_slug)
      @service_form = ServiceForm.load_data(slug: service_slug,
                                            topic: service_en&.topic&.slug,
                                            service_en: service_en,
                                            service_el: service_el)
    end

    def update
      @service_form = ServiceForm.new(service_form_params.merge(slug: service_slug))

      if @service_form.valid?
        @service_form.update!

        redirect_to support_interface_root_path, notice: t('.success')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def service_slug
      params.require(:id)
    end

    def service_form_params
      params.require(:service_form).permit(*allowed_form_params)
    end

    def new_service_form_params
      params.require(:service_form).permit(:slug, *allowed_form_params)
    end

    def allowed_form_params
      %i[name_en description_en website_en information_en name_el description_el website_el information_el topic]
    end

    helper_method :available_topics

    def available_topics
      Topic.locale(I18n.locale).subtopics
    end
  end
end

app/controllers/support_interface/sessions_controller.rb
module SupportInterface
  class SessionsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: :create
    skip_before_action :authenticate_user!, only: %i[new create failure]

    def create
      user = User.find_by(provider: auth_hash['provider'], uid: auth_hash['uid'], user_type: 'support_user')
      return create_user_and_request_activation if user.nil?

      session[:user_id] = user.id
      redirect_to support_interface_root_path, notice: t('.success')
    end

    def destroy
      session[:user_id] = nil
      redirect_to new_support_interface_session_path, notice: t('.success')
    end

    def failure
      redirect_to new_support_interface_session_path, notice: t('.success')
    end

    protected

    def auth_hash
      request.env['omniauth.auth']
    end

    def create_user_and_request_activation
      User.create_from_omniauth(auth_hash)
      redirect_to logout_path, notice: t('.activation_required')
    end
  end
end

app/controllers/support_interface/topics_controller.rb
module SupportInterface
  class TopicsController < ApplicationController
    def index
      @topics = Topic.locale(I18n.locale).all
    end

    def new
      @topic_form = TopicForm.new
    end

    def create
      @topic_form = TopicForm.new(topic_params)
      if @topic_form.valid?(:new)
        @topic_form.save!
        redirect_to support_interface_root_path, notice: 'Topic created successfully'
      else
        render 'new', status: :unprocessable_entity
      end
    end

    private

    def topic_params
      params.require(:topic_form).permit(:slug, :name_en, :description_en, :name_el, :description_el, :topic)
    end

    helper_method :available_topics

    def available_topics
      Topic.locale(I18n.locale).top_level_topics
    end
  end
end

app/views/support_interface/services/edit.html.erb
<%= simple_form_for @service_form, url: support_interface_service_path, method: :patch, wrapper: :vertical_form do |form| %>
  <%= form.input :slug, disabled: true, readonly: true %>

  <div class='py-4'>
    <h2><%= I18n.t('english') %></h2>

    <%= form.input :name_en %>
    <%= form.input :description_en, as: :text%>
    <%= form.input :website_en %>
    <%= form.input :information_en, as: :text %>
  </div>

  <div class='py-4'>
    <h2><%= I18n.t('greek') %></h2>

    <%= form.input :name_el %>
    <%= form.input :description_el, as: :text %>
    <%= form.input :website_el %>
    <%= form.input :information_el, as: :text %>
  </div>

  <%= form.input :topic, as: :select, collection: available_topics, value_method: :slug, selected: @service_form.topic, include_blank: true  %>

  <%= form.submit I18n.t('edit') %>
<% end %>

app/views/support_interface/services/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <%= link_to t('new_service'), new_support_interface_service_path, class: 'btn btn-primary float-right' %>

      <table class="table">
        <thead>
          <tr>
            <th scope="col">slug</th>
            <th scope="col">Name</th>
            <th scope="col">Website</th>
            <th scope="col">Topic</th>
          </tr>
        </thead>
        <tbody>
          <% @services.each do |service| %>
            <tr>
              <th scope="row"><%= service.slug %></th>
              <td><%= service.name %></td>
              <td><%= service.website %></td>
              <td><%= service.topic&.name %></td>
              <td><%= link_to 'Edit', edit_support_interface_service_path(service) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/support_interface/services/new.html.erb
<%= simple_form_for @service_form, url: support_interface_services_path, method: :post, wrapper: :vertical_form do |form| %>
  <%= form.error_notification %>

  <%= form.input :slug %>

  <div class='py-4'>
    <h2><%= I18n.t('english') %></h2>

    <%= form.input :name_en %>
    <%= form.input :description_en, as: :text%>
    <%= form.input :website_en %>
    <%= form.input :information_en, as: :text %>
  </div>

  <div class='py-4'>
    <h2><%= I18n.t('greek') %></h2>

    <%= form.input :name_el %>
    <%= form.input :description_el, as: :text %>
    <%= form.input :website_el %>
    <%= form.input :information_el, as: :text %>
  </div>

  <%= form.input :topic, as: :select, collection: available_topics, value_method: :slug, include_blank: true %>

  <%= form.submit I18n.t('create') %>
<% end %>