config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root 'portal#index'

    resources :search, only: :index, as: :searches
    resources :services, only: :show

    resources :topics, only: :show, path: 'browse' do
      resources :topics, only: :show, as: :subtopic, path: ''
    end

    resource :status, only: [:show]

    namespace :support_interface, path: '/support' do
      root 'services#index'

      resources :topics, only: %i[index new create]
      resources :sessions, only: :new
      resources :services, only: %i[new create update edit]
    end
  end

  post '/auth/:provider/callback', to: 'support_interface/sessions#create'
  post '/auth/failure', to: 'support_interface/sessions#failure'
  get '/auth/failure', to: 'support_interface/sessions#failure'
  get '/logout', to: 'support_interface/sessions#destroy'
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :topic, optional: true
  has_many :topics, -> { order(:name) }

  has_many :service_topics, -> { order(:name) }
  has_many :services, through: :service_topics

  scope :locale, ->(locale) { where(locale: locale) }
  scope :top_level_topics, -> { includes(:service_topics).where(service_topics: { id: nil }).where(topic: nil) }
  scope :subtopics, -> { where.not(topic_id: nil) }

  validates :locale, :name, :description, presence: true

  def to_param
    slug
  end
end

app/controllers/support_interface/topics_controller.rb
module SupportInterface
  class TopicsController < ApplicationController
    def index
      @topics = Topic.locale(I18n.locale).all
    end

    def new
      @topic_form = TopicForm.new
    end

    def create
      @topic_form = TopicForm.new(topic_params)
      if @topic_form.valid?(:new)
        @topic_form.save!
        redirect_to support_interface_root_path, notice: 'Topic created successfully'
      else
        render 'new', status: :unprocessable_entity
      end
    end

    private

    def topic_params
      params.require(:topic_form).permit(:slug, :name_en, :description_en, :name_el, :description_el, :topic)
    end

    helper_method :available_topics

    def available_topics
      Topic.locale(I18n.locale).top_level_topics
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def show
    @topic = Topic.locale(I18n.locale).find_by(slug: topic_id)
    @parent_topic = @topic.topic.presence

    render 'show'
  end

  private

  def topic_id
    params.permit(:id)[:id]
  end
end

app/views/topics/show.html.erb
<% content_for :page_title, "#{@topic.name} - ISTOS.CY"  %>

<% add_parent_breadcrumb_link t('home'), root_path %>
<% if @parent_topic %>
  <% add_parent_breadcrumb_link @parent_topic.name, topic_path(@parent_topic) %>
<% end %>

<% content_for :title, @topic.name %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% if @topic.topics.any? %>
        <h1><%= @topic.name %></h1>
        <p class="lead py-2">
        <%= @topic.description %>
        </p>

        <ul class='list-unstyled'>
          <% @topic.topics.each do |subtopic| %>
            <li> <%= link_to subtopic.name, topic_subtopic_path(@topic, subtopic) %></li>
          <% end %>
        </ul>
      <% end %>

      <% if @topic.services.any? %>
        <div class="row">
          <div class="col-md-3">
            <ul class="list-group d-none d-sm-block mb-4">
              <% @parent_topic.topics.each do |topic| %>
                <% if topic.eql?(@topic) %>
                  <%= link_to topic.name, topic_path(topic), class: "list-group-item list-group-item-action active" %>
                <% else %>
                  <%= link_to topic.name, topic_path(topic), class: "list-group-item list-group-item-action" %>
                <% end %>
              <% end %>
            </ul>
          </div>

          <div class="col-md-9">
            <h1><%= @topic.name %></h1>
            <p class="lead py-2">
            <%= @topic.description %>
            </p>
            <ul class='list-unstyled'>
              <% @topic.services.each do |service| %>
                <li>
                  <%= link_to service.name, service_path(service) %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>