config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root 'portal#index'

    resources :search, only: :index, as: :searches
    resources :services, only: :show

    resources :topics, only: :show, path: 'browse' do
      resources :topics, only: :show, as: :subtopic, path: ''
    end

    resource :status, only: [:show]

    namespace :support_interface, path: '/support' do
      root 'services#index'

      resources :topics, only: %i[index new create]
      resources :sessions, only: :new
      resources :services, only: %i[new create update edit]
    end
  end

  post '/auth/:provider/callback', to: 'support_interface/sessions#create'
  post '/auth/failure', to: 'support_interface/sessions#failure'
  get '/auth/failure', to: 'support_interface/sessions#failure'
  get '/logout', to: 'support_interface/sessions#destroy'
end

app/views/layouts/_change_locale.html.erb
<% if locale == :en %>
  <%= link_to "#{t('greek', locale: :el)}", url_for(locale: :el), class: 'btn btn-outline-secondary' %>
<% else %>
  <%= link_to "#{t('english', locale: :en)}", url_for(locale: :en), class: 'btn btn-outline-secondary' %>
<% end %>

app/views/layouts/_og.html.erb
<% if @service&.persisted? %>
  <meta name="title" content="ISTOS.CY - <%= @service.name %>"/>
  <meta name="description" content="<%= @service.description %>"/>
  <meta name="keywords" content="" />

  <meta property="og:title" content="ISTOS.CY - <%= @service.name %>"/>
  <meta property="og:description" content="<%= @service.description %>"/>
  <meta property="og:image" content="<%= image_url("webg.png") %>" />
  <meta property="og:url" content="<%= service_url %>" />
  <meta property="og:type" content="website" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="ISTOS.CY - <%= @service.name %>" />
  <meta name="twitter:description" content="<%= @service.description %>"/>
  <meta name="twitter:image" content="<%= image_url("webg.png") %>" />
  <meta name="twitter:site" content="<%= service_url %>" />
<% else %>
  <meta name="title" content="<%= I18n.t('welcome', name: 'ISTOS.CY') %>" />
  <meta name="description" content="<%= t('intro') %>"/>
  <meta name="keywords" content="<%= t('tagline') %>" />

  <meta property="og:title" content="<%= I18n.t('welcome', name: 'ISTOS.CY') %>" />
  <meta property="og:description" content="<%= t('intro') %>"/>
  <meta property="og:image" content="<%= image_url("webg.png") %>" />
  <meta property="og:url" content="<%= root_url %>" />
  <meta property="og:type" content="website" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="<%= I18n.t('welcome', name: 'ISTOS.CY') %>" />
  <meta name="twitter:description" content="<%= t('intro') %>"/>
  <meta name="twitter:image" content="<%= image_url("webg.png") %>" />
  <meta name="twitter:site" content="<%= root_url %>" />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang=<%= I18n.locale %>>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <title><%= content_for?(:page_title) ? yield(:page_title) : "ISTOS.CY" %></title>
    <%= render partial: 'layouts/og' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://www.googletagmanager.com/gtag/js?id=G-M068ZL629D" data-turbo-track="reload" async></script>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= favicon_link_tag asset_path('webg.png') %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,900;1,400;1,500;1,900&display=swap" rel="stylesheet">
  </head>
  <body>

    <header>
      <div class="navbar navbar-dark bg-primary">
        <div class="container ">
          <%=link_to 'ISTOS.CY', root_path, class: "navbar-brand" %>
          <%= render partial: 'layouts/change_locale' %>
        </div>
      </div>
    </header>

    <main role="main">
      <%= render_navigation %>

      <%= yield %>
    </main>

    <footer class="text-muted bg-light">
      <div class="container py-4">
        <p class="float-right">
        <a href="#"><%= t('back_to_top') %></a>
        </p>
        <p><%= t('footerline') %></p>
        <hr>
        <p class="float-right">
          <%= t('copyright_html', extract_method: link_to('ExtractMethod', 'https://extractmethod.com'), digital_apps: link_to('DigitalApps', 'https://digitalapps.io')) %>
        </p>
      </div>
    </footer>

  </body>
</html>

app/views/layouts/application_support.html.erb
<!DOCTYPE html>
<html lang=<%= I18n.locale %>>
  <head>
    <title>Support - ISTOS.CY</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,900;1,400;1,500;1,900&display=swap" rel="stylesheet">
  </head>
  <body id='support'>

    <header>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container">
          <%= link_to support_interface_root_path, class: "navbar-brand" do %>
            ISTOS.CY <small>admin</small>
          <% end %>
          <% if current_user&.support_user?  %>
            <%= link_to root_path, class: "navbar-brand" do %>
              ISTOS.CY <small>live</small>
            <% end %>
          <% end %>
          <%= render partial: 'layouts/change_locale' %>
        </div>
      </div>
    </header>
    <main role="main">
      <% if notice %>
        <div class="alert alert-info">
          <div class="container">
            <%= notice %>
          </div>
        </div>
      <% end %>
      <div class="container py-5">
        <%= yield %>
      </div>
    </main>
    <footer class="text-muted">
      <div class="container mb-4"></div>
    </footer>
  </body>
</html>